export type MemoryChunk = { label: string };

export const MEMORY_CHUNKS: MemoryChunk[] = [
  { label: 'Matthew 1–7' },
  { label: 'Matthew 8–14' },
  { label: 'Matthew 15–21' },
  { label: 'Matthew 22–28' },
  { label: 'Mark 1–5' },
  { label: 'Mark 6–10' },
  { label: 'Mark 11–16' },
  { label: 'Luke 1–6' },
  { label: 'Luke 7–12' },
  { label: 'Luke 13–18' },
  { label: 'Luke 19–24' },
  { label: 'John 1–7' },
  { label: 'John 8–14' },
  { label: 'John 15–21' },
  { label: 'Acts 1–7' },
  { label: 'Acts 8–14' },
  { label: 'Acts 15–21' },
  { label: 'Acts 22–28' },
  { label: 'Romans 1–5' },
  { label: 'Romans 6–11' },
  { label: 'Romans 12–16' },
  { label: '1 Corinthians 1–5' },
  { label: '1 Corinthians 6–10' },
  { label: '1 Corinthians 11–16' },
  { label: '2 Corinthians 1–7' },
  { label: '2 Corinthians 8–13' },
  { label: 'Galatians' },
  { label: 'Ephesians' },
  { label: 'Philippians' },
  { label: 'Colossians' },
  { label: '1 Thessalonians' },
  { label: '2 Thessalonians' },
  { label: '1 Timothy' },
  { label: '2 Timothy' },
  { label: 'Titus' },
  { label: 'Philemon' },
  { label: 'Hebrews 1–7' },
  { label: 'Hebrews 8–13' },
  { label: 'James' },
  { label: '1 Peter' },
  { label: '2 Peter' },
  { label: '1 John' },
  { label: '2 John' },
  { label: '3 John' },
  { label: 'Jude' },
  { label: 'Revelation 1–7' },
  { label: 'Revelation 8–15' },
  { label: 'Revelation 16–22' },
];
